Stuff:
	 gcc -o store_client -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing  -g store_clnt.c store_client.c store_xdr.c -lnsl -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl
	 gcc -o store_server -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing  -g store_svc.c store_server.c store_xdr.c -lnsl -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl

