/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "store.h"


void
online_store_1(char *host)
{
	CLIENT *clnt;
	Producto  *result_1;
	char  obtenerproducto_1_arg;
	int  *result_2;
	Producto  comprarproducto_1_arg;
	int  *result_3;
	Producto  quitarproducto_1_arg;
	int  *result_4;
	Usuario  iniciarsesion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ONLINE_STORE, VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	Usuario* yo = malloc(sizeof(Usuario));
   	printf("Inicie sesión para continuar \nUsuario: ");
   	scanf("%15s",yo->login);
   	printf("Contraseña: ");
   	scanf("%15s",yo->pass);
   	result_4 = iniciarsesion_1(yo, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else if((*result_4) == 1){
      	printf("Bienvenido de nuevo\n");
      	/*TODO: put stuff right here */
      	result_1 = obtenerproducto_1(&obtenerproducto_1_arg, clnt);
		if (result_1 == (Producto *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		result_2 = comprarproducto_1(&comprarproducto_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		result_3 = quitarproducto_1(&quitarproducto_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
   	} else {
   		printf("No se encuentra el usuario\n");
   	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	online_store_1 (host);
exit (0);
}
