/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "store.h"


void
online_store_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	Usuario  iniciarsesion_1_arg;
	char * *result_2;
	char * consultarproductos_1_arg;
	char * *result_3;
	char * obtenerproducto_1_arg;
	int  *result_4;
	int  comprarproducto_1_arg;
	int  *result_5;
	int  quitarproducto_1_arg;
	int  *result_6;
	Producto  agregarproducto_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ONLINE_STORE, VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
int opc;
   char *criteria = malloc(sizeof(char)*200);
   Usuario* yo = malloc(sizeof(Usuario));
   Producto* p = malloc(sizeof(Producto));
   printf("Usuario: ");
   scanf("%15s",yo->login);
   printf("Contraseña: ");
   scanf("%15s",yo->pass);
   result_1 = iniciarsesion_1(yo, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else if(*result_1 == 1){
      do{ //Admin User
         printf("\nAdministrador \n1. Mostrar productos \n2. Buscar un producto \n3. Agregar productos \n4. Cerrar sesión y salir\nSeleccione una opción: ");
         scanf("%d",&opc);
         switch(opc){
            case 1:
            	consultarproductos_1_arg = "";
            	result_2 = consultarproductos_1(&consultarproductos_1_arg, clnt);
					if (result_2 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
               	printf("%s",*result_2);
               	break;
            case 2:
               printf("Busqueda: ");
               scanf("%s",criteria);
               result_3 = obtenerproducto_1(&criteria, clnt);
				if (result_3 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
               printf("%s", *result_3);
               break;
            case 3: //Add products
            	printf("Introduce a continuación los datos del producto\n");
               printf("idCategoria: ");
               setbuf( stdin, NULL ); 
               scanf("%d",&(p->idCategoria));
               printf("Nombre: ");
               setbuf( stdin, NULL ); 
               gets(p->producto);
               printf("Precio: ");
               setbuf( stdin, NULL ); 
               scanf("%f",&(p->precio));
               printf("Existencia: ");
               setbuf( stdin, NULL ); 
               scanf("%d",&(p->existencia));
               printf("Descripción: ");
               setbuf( stdin, NULL ); 
               gets(p->descripcion);
            result_6 = agregarproducto_1(p, clnt);
			if (result_6 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
			}
               break;
            case 4:
               printf("Bye\n");
               break;
            default:
               break;
         }
      }while(opc!=4);
   }else if(*result_1 > 0){
      do{ //Common User
         printf("\n1. Mostrar productos \n2. Buscar un producto \n3. Comprar productos \n4. Cerrar sesión y salir\nSeleccione una opción: ");
         scanf("%d",&opc);
         switch(opc){
            case 1:
            	consultarproductos_1_arg = "";
            	result_2 = consultarproductos_1(&consultarproductos_1_arg, clnt);
					if (result_2 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
               	printf("%s",*result_2);
               	break;
            case 2:
               printf("Busqueda: ");
               scanf("%s",criteria);
               result_3 = obtenerproducto_1(&criteria, clnt);
				if (result_3 == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
               printf("%s", *result_3);
               break;
            case 3: //Buy products
	            result_4 = comprarproducto_1(&comprarproducto_1_arg, clnt);
				if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
				}
				result_5 = quitarproducto_1(&quitarproducto_1_arg, clnt);
				if (result_5 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
               break;
            case 4:
               printf("Bye\n");
               break;
            default:
               break;
         }
      }while(opc!=4);
   } else {
      printf("No se encuentra el usuario\n");
   }
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	online_store_1 (host);
exit (0);
}
