/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "store.h"
#include <stdio.h>
#include <stdlib.h>
#include <mysql.h>

MYSQL *conn;
MYSQL_RES *res;
MYSQL_ROW row;
char *server = "127.0.0.1";
char *user = "root";
char *password = "n0m3l0s3"; /* set me first */
char *database = "carritocompras";

void conectarBD(){
   conn = mysql_init(NULL);
   /* Connect to database */
   if (!mysql_real_connect(conn, server,
         user, password, database, 0, NULL, 0)) {
      fprintf(stderr, "%s\n", mysql_error(conn));
      exit(1);
   }
}

void desconectarBD(){
   /* close connection */
   mysql_free_result(res);
   mysql_close(conn);
}

Producto *
obtenerproducto_1_svc(char *argp, struct svc_req *rqstp)
{
	static Producto  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
comprarproducto_1_svc(Producto *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
quitarproducto_1_svc(Producto *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
iniciarsesion_1_svc(Usuario *argp, struct svc_req *rqstp)
{
	static int  result;
	conectarBD();
   char query[500];
   sprintf(query,"select * from usuario where tx_login='%s' and tx_password='%s'",argp->login,argp->pass);
   /* send SQL query */
   if (mysql_query(conn, query)) {
      fprintf(stderr, "%s\n", mysql_error(conn));
      result = 0;
   }
   res = mysql_use_result(conn);
   /* output table name */
   if ((row = mysql_fetch_row(res)) != NULL) {
      result = 1;
   } else {
      desconectarBD();
      result = 0;
   }
   desconectarBD();

	return &result;
}
