/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STORE_H_RPCGEN
#define _STORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Usuario {
	char login[15];
	char pass[15];
};
typedef struct Usuario Usuario;

struct Producto {
	int idCategoria;
	char producto[80];
	float precio;
	int existencia;
	char descripcion[255];
};
typedef struct Producto Producto;

#define ONLINE_STORE 0x20000001
#define VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define iniciarSesion 1
extern  int * iniciarsesion_1(Usuario *, CLIENT *);
extern  int * iniciarsesion_1_svc(Usuario *, struct svc_req *);
#define consultarProductos 2
extern  char ** consultarproductos_1(char **, CLIENT *);
extern  char ** consultarproductos_1_svc(char **, struct svc_req *);
#define obtenerProducto 3
extern  char ** obtenerproducto_1(char **, CLIENT *);
extern  char ** obtenerproducto_1_svc(char **, struct svc_req *);
#define comprarProducto 4
extern  int * comprarproducto_1(int *, CLIENT *);
extern  int * comprarproducto_1_svc(int *, struct svc_req *);
#define quitarProducto 5
extern  int * quitarproducto_1(int *, CLIENT *);
extern  int * quitarproducto_1_svc(int *, struct svc_req *);
#define agregarProducto 6
extern  int * agregarproducto_1(Producto *, CLIENT *);
extern  int * agregarproducto_1_svc(Producto *, struct svc_req *);
extern int online_store_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define iniciarSesion 1
extern  int * iniciarsesion_1();
extern  int * iniciarsesion_1_svc();
#define consultarProductos 2
extern  char ** consultarproductos_1();
extern  char ** consultarproductos_1_svc();
#define obtenerProducto 3
extern  char ** obtenerproducto_1();
extern  char ** obtenerproducto_1_svc();
#define comprarProducto 4
extern  int * comprarproducto_1();
extern  int * comprarproducto_1_svc();
#define quitarProducto 5
extern  int * quitarproducto_1();
extern  int * quitarproducto_1_svc();
#define agregarProducto 6
extern  int * agregarproducto_1();
extern  int * agregarproducto_1_svc();
extern int online_store_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Usuario (XDR *, Usuario*);
extern  bool_t xdr_Producto (XDR *, Producto*);

#else /* K&R C */
extern bool_t xdr_Usuario ();
extern bool_t xdr_Producto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STORE_H_RPCGEN */
