-- MySQL Script generated by MySQL Workbench
-- dom 25 may 2014 18:59:24 CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carritocompras
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carritocompras` ;
CREATE SCHEMA IF NOT EXISTS `carritocompras` DEFAULT CHARACTER SET latin1 ;
USE `carritocompras` ;

-- -----------------------------------------------------
-- Table `carritocompras`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`categoria` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`categoria` (
  `id_categoria` INT(10) NOT NULL AUTO_INCREMENT,
  `id_padre` INT(10) NOT NULL,
  `nb_categoria` VARCHAR(50) NOT NULL,
  `tx_descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `FKtbl01_cate758351_idx` (`id_categoria` ASC),
  CONSTRAINT `FKtbl01_cate758351`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `carritocompras`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`atributo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`atributo` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`atributo` (
  `id_categoria` INT(10) NOT NULL,
  `id_atributo` INT(10) NOT NULL,
  `nb_atributo` VARCHAR(256) NOT NULL,
  `tx_descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_categoria`, `id_atributo`),
  INDEX `FKtbl02_atri921981_idx` (`id_categoria` ASC),
  CONSTRAINT `FKtbl02_atri921981`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `carritocompras`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`producto` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`producto` (
  `id_producto` INT(10) NOT NULL,
  `id_categoria` INT(10) NOT NULL,
  `nb_producto` VARCHAR(80) NOT NULL,
  `nu_precio` FLOAT NOT NULL,
  `nu_existencia` INT(10) NOT NULL,
  `dx_descripcion` VARCHAR(255) NOT NULL,
  `bl_fotografia` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`, `id_categoria`),
  INDEX `FKtbl03_prod205652_idx` (`id_categoria` ASC),
  CONSTRAINT `FKtbl03_prod205652`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `carritocompras`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`producto_atributo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`producto_atributo` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`producto_atributo` (
  `id_producto` INT(10) NOT NULL,
  `id_atributo` INT(10) NOT NULL,
  `id_categoria` INT(10) NOT NULL,
  `tx_valor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_atributo`, `id_categoria`),
  INDEX `FKtbl04_prod923596_idx` (`id_producto` ASC, `id_categoria` ASC),
  INDEX `FKtbl04_prod539688_idx` (`id_categoria` ASC, `id_atributo` ASC),
  CONSTRAINT `FKtbl04_prod539688`
    FOREIGN KEY (`id_categoria` , `id_atributo`)
    REFERENCES `carritocompras`.`atributo` (`id_categoria` , `id_atributo`),
  CONSTRAINT `FKtbl04_prod923596`
    FOREIGN KEY (`id_producto` , `id_categoria`)
    REFERENCES `carritocompras`.`producto` (`id_producto` , `id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`usuario` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`usuario` (
  `id_usuario` INT(10) NOT NULL AUTO_INCREMENT,
  `tx_login` VARCHAR(15) NOT NULL,
  `tx_password` VARCHAR(15) NOT NULL,
  `nb_usuario` VARCHAR(20) NOT NULL,
  `tx_apa` VARCHAR(20) NOT NULL,
  `tx_apb` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`compra` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`compra` (
  `id_compra` INT(10) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(10) NOT NULL,
  `fh_compra` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_compra`),
  INDEX `FKtbl05_comp240987_idx` (`id_usuario` ASC),
  CONSTRAINT `FKtbl05_comp240987`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `carritocompras`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`producto_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`producto_compra` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`producto_compra` (
  `id_producto` INT(10) NOT NULL,
  `id_compra` INT(10) NOT NULL,
  `id_categoria` INT(10) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_compra`, `id_categoria`),
  INDEX `FKtbl06_prod758312_idx` (`id_producto` ASC, `id_categoria` ASC),
  INDEX `FKtbl06_prod179180_idx` (`id_compra` ASC),
  CONSTRAINT `FKtbl06_prod179180`
    FOREIGN KEY (`id_compra`)
    REFERENCES `carritocompras`.`compra` (`id_compra`),
  CONSTRAINT `FKtbl06_prod758312`
    FOREIGN KEY (`id_producto` , `id_categoria`)
    REFERENCES `carritocompras`.`producto` (`id_producto` , `id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carritocompras`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carritocompras`.`direccion` ;

CREATE TABLE IF NOT EXISTS `carritocompras`.`direccion` (
  `id_direccion` INT(10) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(10) NOT NULL,
  `nb_calle` VARCHAR(50) NOT NULL,
  `nb_colonia` VARCHAR(100) NOT NULL,
  `tx_cp` VARCHAR(6) NOT NULL,
  `nb_ciudad` VARCHAR(50) NOT NULL,
  `nb_estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `FKtbl08_dire695188_idx` (`id_usuario` ASC),
  CONSTRAINT `FKtbl08_dire695188`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `carritocompras`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
